source 'https://rubygems.org'

# Padrino supports Ruby version 2.2.2 and later
# ruby '2.3.7'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Optional JSON codec (faster performance)
# gem 'oj'

# Project requirements
gem 'rake'

# Component requirements
gem 'dm-sqlite-adapter'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-constraints'
gem 'dm-aggregates'
gem 'dm-types'
gem 'dm-core'

gem 'pry'
gem 'shrine'

# configs
gem 'jbuilder', '~> 2.0'
gem 'rack-cors'

# send files
# gem 'paperclip'
gem 'carrierwave'


# Test requirements
gem 'mocha', :group => 'test', :require => false

# Padrino Stable Gem
gem 'padrino', '0.14.3'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core support gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.14.3'
# end
